### ISSUE TITLE
Composition not rendering on mobile (iOS)

### ISSUE THREAD

**Issue by jackien1** [diffusionstudio/core#35]
The issue might be related to the HTML track.

**Comment by k9p5** [comment]
Which model and version does this affect?

**Comment by jackien1** [comment]
I'm currently on version ^1.1.0. Do you mean backend model? We have it set to 'webgpu' not sure if it becomes 'webgl' on mobile.

**Comment by holman** [comment]
Not sure if this is the same or not, but I'll drop it in here for posterity: I'm seeing a black screen when trying to play a video on macOS, Safari 18.2. Audio plays, but video doesn't appear. Strangely, rendering it to a separate file does export the video correctly. This is the latest Sequoia 15.2 beta, though, and I was leaning on it being a beta problem instead of a problem here (since it had recently changed for me). Maybe iOS is the same, if you're on a beta there?

**Comment by k9p5** [comment]
When running @diffusionstudio/core on Safari 17.6 and MacOs Sonoma I'm not facing any issues like that. Have you tried forcing WebGL2 (`new Composition({ backend: 'webgl' })`)?

**Comment by k9p5** [comment]
> I'm currently on version ^1.1.0. Do you mean backend model? We have it set to 'webgpu' not sure if it becomes 'webgl' on mobile.

WebCodecs was added to iOS Safari in September this year. If the user hasn't updated the device, he won't be able to render videos

**Comment by jackien1** [comment]
It looks like the issue isn't HTML but the audio track.
